version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: my-secret
      MYSQL_DATABASE: expense_tracker
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - expense-network

  redis:
    image: redis:7.2
    container_name: redis-server
    command: >
      redis-server --requirepass my-redis
    ports:
      - "16379:6379"
    networks:
      - expense-network

  expense-tracker:
    image: expense-tracker
    container_name: expense-tracker
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      db_host: db
      db_name: expense_tracker
      db_port: 3306
      db_username: root
      db_password: my-secret
      redis_host: redis
      redis_port: 6379
      redis_password: my-redis
      secret: F867KS86JD867HF86KF04985926D96C90030DD58429D2751AC1BDB645BY654C0123456789ABCDEF0123456789ABCDEF
    depends_on:
      - db
      - redis
    networks:
      - expense-network
networks:
  expense-network:

volumes:
  mysql_data:
