server:
  port: 8080

spring:
  application:
    name: expense-tracker
  main:
    banner-mode: off

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${db_host}:${db_port}/${db_name}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${db_username}
    password: ${db_password}
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    enabled: true
    table: _flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 1


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework: info
    com.snapp: DEBUG