server:
  port: 8080

spring:
  application:
    name: expense-tracker
  main:
    banner-mode: off

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${db_host}:${db_port}/${db_name}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${db_username}
    password: ${db_password}
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    enabled: true
    table: _flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 1
  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}
      password: ${redis_password}

  modulith:
    events:
      externalization:
        enabled: true
      jdbc:
        schema: expense_tracker
        table: events
        transactional: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    root: INFO
    org.springframework: info
    com.snapp: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.transaction.interceptor: DEBUG

app:
  access-token-ttl: 1800000
  refresh-token-ttl: 604800000
  secret: ${secret}

